"""Offline bound on how often the Stage 4 kernel could refuse a CLEAN scenario.

No model call, no network, no cost. For every scenario in a clean trace this
takes the Stage 3 ledger and resolves ``kernel_verdict`` under two scripted
analyses that bracket what the analysis step could possibly return:

* **optimistic** -- every admissible item ``supports``, nothing contradicts, no
  embedded commands. This must be CLEAR for essentially every clean scenario.
  Anything else is a logic bug in the verdict, not a modelling result: it would
  mean the kernel refuses work even when the evidence is maximally favourable,
  which is gate *starvation* -- the failure that took the old ``D4_OutputGate``
  to 72% blocking including 7 correct diagnoses.

* **pessimistic** -- every admissible item ``irrelevant``, nothing contradicts,
  no embedded commands. This is what happens when the analysis finds no link at
  all: RESTRICT via ``NO_ADMISSIBLE_SUPPORT``. The count says how much of the
  clean pass-through rate rests on the LLM finding at least one supporting link.

Both passes use ``certainty="definitive"``, the strictest claim available, so
nothing here is flattered by a hedged diagnosis.

THIS IS A BOUND ON THE VERDICT LOGIC, NOT A PREDICTION OF LIVE BEHAVIOUR. The
real clean pass-through rate depends on what ``kernel_analyze`` returns and is
unmeasured until ``scripts/run_kernel_offline.py`` is run against a live model.
"""

from __future__ import annotations

import argparse
import collections
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from core.kernel import (CLEAR, REASON_NO_SUPPORT, RESTRICT, UNSAFE,  # noqa: E402
                         _admissible_ids, kernel_verdict, scripted_analysis)
from core.ledger import ledger_from_trace  # noqa: E402


def load_trace(path):
    with open(path, encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]


def scenarios(events):
    return sorted(set(e.get("scenario_id") for e in events
                      if e.get("scenario_id") is not None))


def run(path):
    events = load_trace(path)
    rows = []
    for sid in scenarios(events):
        ledger = ledger_from_trace(events, sid)
        admissible = _admissible_ids(ledger)
        optimistic = kernel_verdict(scripted_analysis(ledger, "supports"), ledger)
        pessimistic = kernel_verdict(scripted_analysis(ledger, "irrelevant"), ledger)
        rows.append({
            "scenario_id": sid,
            "spans": len(ledger.items),
            "admissible": len(admissible),
            "optimistic": optimistic.state,
            "optimistic_codes": list(optimistic.reason_codes),
            "pessimistic": pessimistic.state,
            "pessimistic_codes": list(pessimistic.reason_codes),
        })
    return rows


def render(path, rows):
    n = len(rows)
    opt = collections.Counter(r["optimistic"] for r in rows)
    pes = collections.Counter(r["pessimistic"] for r in rows)
    L = []
    add = L.append
    add("# Stage 4 -- offline starvation estimate")
    add("")
    add("Generated by `scripts/estimate_starvation.py` over `{}`. No model call, "
        "no network, no randomness.".format(os.path.basename(path)))
    add("")
    add("Two scripted analyses bracket what the analysis step could return, and "
        "`kernel_verdict` -- the pure half -- resolves each. Both use "
        "`certainty=\"definitive\"`, the strictest claim available.")
    add("")
    add("| pass | what the analysis says | CLEAR | RESTRICT | UNSAFE |")
    add("|---|---|---:|---:|---:|")
    add("| optimistic | every admissible item `supports` | {} | {} | {} |".format(
        opt[CLEAR], opt[RESTRICT], opt[UNSAFE]))
    add("| pessimistic | every admissible item `irrelevant` | {} | {} | {} |".format(
        pes[CLEAR], pes[RESTRICT], pes[UNSAFE]))
    add("")
    add("Over **{}** clean scenarios.".format(n))
    add("")
    bad = [r for r in rows if r["optimistic"] != CLEAR]
    if bad:
        add("**{} scenarios are not CLEAR on the optimistic pass.** That is a "
            "logic bug in the verdict, not a modelling result -- the kernel is "
            "refusing work under maximally favourable evidence.".format(len(bad)))
        add("")
        add("| scenario | spans | admissible items | state | reason codes |")
        add("|---:|---:|---:|---|---|")
        for r in bad:
            add("| {} | {} | {} | {} | {} |".format(
                r["scenario_id"], r["spans"], r["admissible"], r["optimistic"],
                ", ".join("`{}`".format(c) for c in r["optimistic_codes"]) or "-"))
        add("")
    else:
        add("**The optimistic pass is CLEAR for every clean scenario ({}/{}).** "
            "The verdict logic does not starve: SUPPORT_ONLY evidence alone "
            "authorizes a definitive claim, which is what Stage 3's 325-of-447 "
            "demotion rate requires of it.".format(opt[CLEAR], n))
        add("")
    wrong_code = [r for r in rows
                  if r["pessimistic"] == RESTRICT
                  and REASON_NO_SUPPORT not in r["pessimistic_codes"]]
    add("**The pessimistic pass is RESTRICT for {}/{} scenarios**, every one via "
        "`{}`{}. That is the share of the clean arm whose pass-through rests "
        "entirely on the analysis step finding at least one supporting link. It "
        "is the quantity a live run measures and this script cannot."
        .format(pes[RESTRICT], n, REASON_NO_SUPPORT,
                "" if not wrong_code else " except {} with other codes".format(
                    len(wrong_code))))
    add("")
    empty = [r for r in rows if r["admissible"] == 0]
    add("Scenarios with **no admissible evidence at all**: {}. (Those cannot be "
        "CLEAR on either pass, and are counted above rather than excluded.)"
        .format(len(empty)))
    add("")
    add("This is a bound on the verdict logic, **not a prediction of live "
        "behaviour**. The clean pass-through rate is unmeasured until "
        "`scripts/run_kernel_offline.py` is run against a live model.")
    add("")
    return "\n".join(L) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--trace", default=os.path.join(_ROOT, "run_clean.jsonl"))
    ap.add_argument("--out", default=os.path.join(_HERE, "stage4_starvation.md"))
    args = ap.parse_args(argv)

    if not os.path.exists(args.trace):
        print("no trace at {}".format(args.trace))
        return 1
    rows = run(args.trace)
    report = render(args.trace, rows)
    with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(report)

    opt = collections.Counter(r["optimistic"] for r in rows)
    pes = collections.Counter(r["pessimistic"] for r in rows)
    print("scenarios: {}".format(len(rows)))
    print("optimistic  CLEAR {:>3}  RESTRICT {:>3}  UNSAFE {:>3}".format(
        opt[CLEAR], opt[RESTRICT], opt[UNSAFE]))
    print("pessimistic CLEAR {:>3}  RESTRICT {:>3}  UNSAFE {:>3}".format(
        pes[CLEAR], pes[RESTRICT], pes[UNSAFE]))
    print("wrote {}".format(args.out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
